### ISSUE TITLE
[ERROR] Nonfunctional?

### ISSUE THREAD

**Issue by NNickey** [jbrooksuk/SoundRain#3]
![image](https://cloud.githubusercontent.com/assets/3466265/11053767/22c782e0-8721-11e5-89c2-0ddc3f28313b.png)
![image](https://cloud.githubusercontent.com/assets/3466265/11053773/2de844d4-8721-11e5-8e42-5a23de788e69.png)

*Code Section*
```javascript
var SoundRain = require('soundrain');
var Song = new SoundRain(messageSplit[1], './soundrain');
sendmsg(channelID,"Downloading Soundcloud link.",5)
Song.on('error', function(err) {
	if (err) {
		sendmsg(channelID,"Error with link..",4)
		throw err;
	}
}).on('done', function(file) {
	sendmsg(channelID,"Soundcloud passed, streaming audio.",4)
	bot.testAudio({
		channel: "92733289407725568",
		file: file
	});
});
sendmsg(channelID,"Attempting SoundCloud Stream",4)
```

Node.js error
```
!scstream http://soundcloud.com/jbrooksuk/twisted-beat-sample-at
----------
C:\Users\Administrator\Desktop\DiscordBot\node_modules\soundrain\index.js:66
                        self.download(self.parse(self.tracks[0]));
                                                            ^

TypeError: Cannot read property '0' of null
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\DiscordBot\no
de_modules\soundrain\index.js:66:40)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by 110Percent** [comment]
I'm getting the same error here. The dev doesn't seem to be active on this module anymore. :(

**Comment by jbrooksuk** [comment]
Sorry guys. It looks like this method simply doesn't work now. If someone has a better idea I am happy to implement it.
